[package]
name = "sql-index-simulator-guest"
version = "0.1.0"
description = "SQL Index Simulator — гостевой Tauri-клиент (лаб. 8)"
authors = ["you"]
edition = "2021"

[lib]
name = "sql_index_simulator_guest_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
