# Sets LAN IPv4 into .env.tauri for Tauri lab8 build.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root '.env.tauri'

$ip = Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object {
    $_.IPAddress -notmatch '^127\.' -and
    $_.IPAddress -notmatch '^169\.254\.'
  } |
  Sort-Object InterfaceMetric |
  Select-Object -First 1 -ExpandProperty IPAddress

if (-not $ip) {
  Write-Host 'No IPv4 found. Edit .env.tauri manually.'
  exit 1
}

$lines = @(
  '# Tauri guest - generated by lab8-set-tauri-ip.ps1'
  'VITE_GUEST_ONLY=true'
  "VITE_API_BASE_URL=http://${ip}:8082/api"
  "VITE_MEDIA_BASE_URL=http://${ip}:9000"
)
Set-Content -Path $envFile -Value $lines -Encoding ascii
Write-Host "OK .env.tauri API=http://${ip}:8082/api"
Write-Host 'Compare with: ipconfig'
